//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageUpload.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class ImageUpload
    {
        public int Id { get; set; }
        
        [DisplayName("Student Name")]
        public string StudentName { get; set; }

        [DisplayName("Upload Image")]
        public string Image_path { get; set; }

        public HttpPostedFileWrapper fileName { get; set; }
    }
}
